V1.6.0
eastgenomics/eggd_vcf2xls_nirvana pull request #58
Opened 2021-12-15 10:48 UTC by Yu-jinKim

## App changes:
- New input to app: `annotations`
- Use htslib asset for tabix
- pip3 install pysam wheel

## Vcf2xls changes:
- remove esp, 1kg, exac AF in vcf2xls
- use annotation input to add custom annotation in the report

2021-12-21 16:26 UTC, pep8speaks commented
Hello @Yu-jinKim! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`resources/home/dnanexus/vcf_integrity_check.py`](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/e229380edcac1fcdc4e106db49470835f2636e1f/resources/home/dnanexus/vcf_integrity_check.py):

> [Line 148:17](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/e229380edcac1fcdc4e106db49470835f2636e1f/resources/home/dnanexus/vcf_integrity_check.py#L148): [E201](https://duckduckgo.com/?q=pep8%20E201) whitespace after '('
> [Line 148:35](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/e229380edcac1fcdc4e106db49470835f2636e1f/resources/home/dnanexus/vcf_integrity_check.py#L148): [E201](https://duckduckgo.com/?q=pep8%20E201) whitespace after '['
> [Line 148:71](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/e229380edcac1fcdc4e106db49470835f2636e1f/resources/home/dnanexus/vcf_integrity_check.py#L148): [E201](https://duckduckgo.com/?q=pep8%20E201) whitespace after '['
> [Line 148:80](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/e229380edcac1fcdc4e106db49470835f2636e1f/resources/home/dnanexus/vcf_integrity_check.py#L148): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 148:86](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/e229380edcac1fcdc4e106db49470835f2636e1f/resources/home/dnanexus/vcf_integrity_check.py#L148): [E202](https://duckduckgo.com/?q=pep8%20E202) whitespace before ')'
> [Line 151:17](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/e229380edcac1fcdc4e106db49470835f2636e1f/resources/home/dnanexus/vcf_integrity_check.py#L151): [E201](https://duckduckgo.com/?q=pep8%20E201) whitespace after '('
> [Line 151:35](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/e229380edcac1fcdc4e106db49470835f2636e1f/resources/home/dnanexus/vcf_integrity_check.py#L151): [E201](https://duckduckgo.com/?q=pep8%20E201) whitespace after '['
> [Line 151:64](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/e229380edcac1fcdc4e106db49470835f2636e1f/resources/home/dnanexus/vcf_integrity_check.py#L151): [E201](https://duckduckgo.com/?q=pep8%20E201) whitespace after '['
> [Line 151:72](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/e229380edcac1fcdc4e106db49470835f2636e1f/resources/home/dnanexus/vcf_integrity_check.py#L151): [E202](https://duckduckgo.com/?q=pep8%20E202) whitespace before ')'
> [Line 152:45](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/e229380edcac1fcdc4e106db49470835f2636e1f/resources/home/dnanexus/vcf_integrity_check.py#L152): [E201](https://duckduckgo.com/?q=pep8%20E201) whitespace after '['
> [Line 158:45](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/e229380edcac1fcdc4e106db49470835f2636e1f/resources/home/dnanexus/vcf_integrity_check.py#L158): [E201](https://duckduckgo.com/?q=pep8%20E201) whitespace after '['
> [Line 158:79](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/e229380edcac1fcdc4e106db49470835f2636e1f/resources/home/dnanexus/vcf_integrity_check.py#L158): [E201](https://duckduckgo.com/?q=pep8%20E201) whitespace after '['
> [Line 158:80](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/e229380edcac1fcdc4e106db49470835f2636e1f/resources/home/dnanexus/vcf_integrity_check.py#L158): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)
> [Line 159:62](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/e229380edcac1fcdc4e106db49470835f2636e1f/resources/home/dnanexus/vcf_integrity_check.py#L159): [E201](https://duckduckgo.com/?q=pep8%20E201) whitespace after '('
> [Line 159:69](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/e229380edcac1fcdc4e106db49470835f2636e1f/resources/home/dnanexus/vcf_integrity_check.py#L159): [E202](https://duckduckgo.com/?q=pep8%20E202) whitespace before ')'

2021-12-22 16:46 UTC, mattgarner requested changes
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/58)* status: all files reviewed, 1 unresolved discussion (waiting on @Yu-jinKim)

___
*[resources/home/dnanexus/vcf2xls_nirvana.pl, line 390 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/58#-MrXzZmr5RHjcKYvvvJL:-MrXzZmsDYAISJGDZitq:b-zg5rx8) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/6a4694bca2bac039d9be32b77796e93165b7cd23/resources/home/dnanexus/vcf2xls_nirvana.pl#L390)):*
> ```Raku
>             # we have one value for that annotation, so assign it to both gt
>             $annotation_hash{$annotation}{$gt2} = $data1;
>           }
> ```

It's possible to have an info field with more values than there are alleles
GT=1/2
e.g. GNOMAD_ALLELE_COUNTS=1,3,2,4,2,1
where this describes the 0/0, 0/1, 0/2, 1/1, 1/2, 2/2 counts in gnomad

The current setup works fine for annotations which are one per allele, but may not behave as expected when this is not the case.



_Code quote:_
```Raku
        if ($grep_annotation) {
          my ($data1, $data2) = split(/,/, $infos{$annotation});

          if (defined $data1) {
            $annotation_hash{$annotation}{$gt1} = $data1;
          }

          if (defined $data2) {
            $annotation_hash{$annotation}{$gt2} = $data2;
          } else {
            # we have one value for that annotation, so assign it to both gt
            $annotation_hash{$annotation}{$gt2} = $data1;
          }
```


<!-- Sent from Reviewable.io -->

2021-12-23 09:50 UTC, Yu-jinKim reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/58)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @mattgarner)

___
*[resources/home/dnanexus/vcf2xls_nirvana.pl, line 390 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/58#-MrXzZmr5RHjcKYvvvJL:-MraggkUDxrl30G13tKl:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/6a4694bca2bac039d9be32b77796e93165b7cd23/resources/home/dnanexus/vcf2xls_nirvana.pl#L390)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

It's possible to have an info field with more values than there are alleles
GT=1/2
e.g. GNOMAD_ALLELE_COUNTS=1,3,2,4,2,1
where this describes the 0/0, 0/1, 0/2, 1/1, 1/2, 2/2 counts in gnomad

The current setup works fine for annotations which are one per allele, but may not behave as expected when this is not the case.

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-23 10:05 UTC, mattgarner approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/58)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)



<!-- Sent from Reviewable.io -->

2021-12-23 10:05 UTC, merged