rip perl spaghetti
eastgenomics/eggd_vcf2xls_nirvana pull request #64
Opened 2022-03-15 18:18 UTC by jethror1

**Structure**
- `generate_workbook.py` :
  -  mostly just argparse related things
  - `main()` calls functions to process vcfs (reading, filtering, formatting etc.) then writing to file
- `columns.py`:
  - functions for splitting INFO and FORMAT/SAMPLE fields to separate columns
- `filters.py`:
  - functions for handling running `bcftools filter` and modifying incorrect field types in VCF header
- `vcf.py`:
  - main functions for doing all the vcf munging, `process()` contains the main logic for this
- `excel.py`:
  - functions for writing to and formatting output Excel file

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64)

2022-03-15 20:59 UTC, mattgarner requested changes
> Reviewed 24 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64)* status: 24 of 36 files reviewed, 19 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[dxapp.json, line 22 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE3j2G2k3Bc7S4Hn-L:-MyE3j2H8CC8bOdVQ-wK:b533s4s) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L22)):*
> ```JSON
>       "class": "string",
>       "optional": true,
>       "help": "Lowercase string of assay report is for (i.e. dias)",
> ```

Are the available options described somewhere?



_Code quote:_
```JSON
(i.e. dias)
```
___
*[dxapp.json, line 38 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE49Lo-PIu2ZENFe3n:-MyE49Lo-PIu2ZENFe3o:b-ubq56f) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L38)):*
> ```JSON
>       "class": "string",
>       "optional": true,
>       "help": "Columns of VCF to exclude from output xlsx",
> ```

Do we handle when the same column is passed to both include and exclude?



_Code quote:_
```JSON
    {
      "name": "exclude",
      "label": "Exclude columns",
      "class": "string",
      "optional": true,
      "help": "Columns of VCF to exclude from output xlsx",
      "group": "generate_workbook.py"
    },
    {
      "name": "include",
      "label": "Include columns",
      "class": "string",
      "optional": true,
      "help": "Columns of VCF to only include in output xlsx",
      "group": "generate_workbook.py"
    },
```
___
*[dxapp.json, line 42 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE8AHK6g-m6EYdl6qA:-MyE8AHK6g-m6EYdl6qB:bzw02e) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L42)):*
> ```JSON
>     },
>     {
>       "name": "include",
> ```

perhaps these inputs which act on columns should all be called `blah_columns` rather than `blah` to make it a more intuitive/clear what they do from the name



_Code quote:_
```JSON
include
```
___
*[dxapp.json, line 54 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE4QBe9wZyc1Zpxmb7:-MyE4QBe9wZyc1Zpxmb8:bn5ssxo) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L54)):*
> ```JSON
>       "class": "string",
>       "optional": true,
>       "help": "Order of fields from VCF in output xlsx columns",
> ```

Does this need to be a complete list of all columns to be displayed? How is a partial list handled?



_Code quote:_
```JSON
"Order of fields from VCF in output xlsx columns"
```
___
*[dxapp.json, line 62 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE4cOW6S_Cc4efANs3:-MyE4cOW6S_Cc4efANs4:b-ytddpr) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L62)):*
> ```JSON
>       "class": "string",
>       "optional": true,
>       "help": "= separated key value pairs of VCF fields to rename in output xlsx",
> ```

Do we correctly handle renaming to an already existing column name?



_Code quote:_
```JSON
"help": "= separated key value pairs of VCF fields to rename in output xlsx",
```
___
*[dxapp.json, line 70 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE4r3S5IgEwcy4q7zb:-MyE4r3S5IgEwcy4q7zc:b-yrptem) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L70)):*
> ```JSON
>       "class": "string",
>       "optional": true,
>       "help": "Filters to apply to variants",
> ```

Would it be helpful to provide a pointer to a description of how the filters should be structured/formatted?



_Code quote:_
```JSON
"Filters to apply to variants"
```
___
*[dxapp.json, line 74 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE5A-kBeHLEzyUXPRa:-MyE5A-kBeHLEzyUXPRb:b-otnjks) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L74)):*
> ```JSON
>     },
>     {
>       "name": "keep",
> ```

Perhaps `keep_filtered` to be consistent with `keep_tmp`



_Code quote:_
```JSON
keep
```
___
*[dxapp.json, line 91 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE8ffEBz4Wa2aZUOQS:-MyE8ffEBz4Wa2aZUOQT:bxuu8ou) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L91)):*
> ```JSON
>     },
>     {
>       "name": "add_name",
> ```

maybe `add_samplename_column`?



_Code quote:_
```JSON
add_name
```
___
*[dxapp.json, line 100 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE8mIN4yxlLtykd5lU:-MyE8mIN4yxlLtykd5lV:b-q3npa4) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L100)):*
> ```JSON
>     },
>     {
>       "name": "sheets",
> ```

Maybe `sheet_names`?



_Code quote:_
```JSON
sheets
```
___
*[dxapp.json, line 104 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE5V9gEanhJw3vJAb9:-MyE5V9gEanhJw3vJAbA:b-plv2k0) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L104)):*
> ```JSON
>       "class": "string",
>       "optional": true,
>       "help": "Names to use for sheets where multiple VCFs are passed",
> ```

Is this one sheet per vcf? How are the names mapped to the vcfs?



_Code quote:_
```JSON
Names to use for sheets where multiple VCFs are passed
```
___
*[dxapp.json, line 108 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE8sZiAZqfdwVqp8WQ:-MyE8sZiAZqfdwVqp8WR:bdnkw0k) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L108)):*
> ```JSON
>     },
>     {
>       "name": "output",
> ```

`output_prefix`?



_Code quote:_
```JSON
output
```
___
*[dxapp.json, line 116 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE5ic20J9C4Y9cF8oQ:-MyE5ic20J9C4Y9cF8oR:bstz8t) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L116)):*
> ```JSON
>     },
>     {
>       "name": "merge",
> ```

Do we error if merge and sheet_names are conflicting?



_Code quote:_
```JSON
"name": "merge"
```
___
*[dxapp.json, line 116 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE9-vj0jKaZadxnl1Z:-MyE9-vj0jKaZadxnl1_:bp1l03t) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L116)):*
> ```JSON
>     },
>     {
>       "name": "merge",
> ```

Not sure what a better name for this is, but something more verbose might be good.
`merge_sheets` is perhaps not quite right since it doesn't merge the filtered/unfiltered sheets but merges vcf sheets



_Code quote:_
```JSON
merge
```
___
*[dxapp.json, line 121 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE9QU8Csiq66K4g4Sa:-MyE9QU8Csiq66K4g4Sb:b-mo5i69) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L121)):*
> ```JSON
>       "optional": true,
>       "default": false,
>       "help": "Determines if to merge multiple VCFs to one sheet",
> ```

How does this behave in combination with option to retaining filtered variants in the filtered sheet. One filtered sheet per vcf? One filtered sheet for all vcfs?



_Code quote:_
```JSON
"Determines if to merge multiple VCFs to one sheet",
```
___
*[dxapp.json, line 129 at r1](https://reviewable.io/reviews/eastgenomics/e [...]

2022-03-16 10:40 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64)* status: 24 of 36 files reviewed, 19 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[dxapp.json, line 22 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE3j2G2k3Bc7S4Hn-L:-MyHGjYtDJQ-O1lY8ktd:b-kej7r1) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L22)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Are the available options described somewhere?
</blockquote></details>

I'm going to remove this option and just rely on `--summary`, the only need for this was to get the things to put in the  dias summary, so can rely on `--summary dias`
___
*[dxapp.json, line 38 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE49Lo-PIu2ZENFe3n:-MyHGoe458KOAMpwrCoh:b-j0ufjj) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L38)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Do we handle when the same column is passed to both include and exclude?
</blockquote></details>

`include / exclude` shouldn't be used together, will add a check for this and add to the readme
___
*[dxapp.json, line 42 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE8AHK6g-m6EYdl6qA:-MyHHCkkDGVq026W-7Ue:bahdczv) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L42)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

perhaps these inputs which act on columns should all be called `blah_columns` rather than `blah` to make it a more intuitive/clear what they do from the name
</blockquote></details>

this is what I had before then changed it for some reason... will switch it back
___
*[dxapp.json, line 54 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE4QBe9wZyc1Zpxmb7:-MyHHVU54_697ilDPpYl:b6n8lxt) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L54)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Does this need to be a complete list of all columns to be displayed? How is a partial list handled?
</blockquote></details>

https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/resources/home/dnanexus/generate_workbook/generate_workbook.py#L75

will add full help to app input
___
*[dxapp.json, line 62 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE4cOW6S_Cc4efANs3:-MyHH_GfAgW22DwOvwXa:bs2aox8) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L62)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Do we correctly handle renaming to an already existing column name?
</blockquote></details>

don't think so, will catch this and raise an error 
___
*[dxapp.json, line 70 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE4r3S5IgEwcy4q7zb:-MyHHgR1BKKriaYZLGdW:bc612x0) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L70)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Would it be helpful to provide a pointer to a description of how the filters should be structured/formatted?
</blockquote></details>

Yep will do, on my to do list to add a section to the  readme, found some comprehensive examples I can link to
___
*[dxapp.json, line 74 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE5A-kBeHLEzyUXPRa:-MyHHoGW6T4jKIdtrRVr:b89r774) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L74)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Perhaps `keep_filtered` to be consistent with `keep_tmp`
</blockquote></details>

good idea, will do
___
*[dxapp.json, line 116 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE5ic20J9C4Y9cF8oQ:-MyHHwkr4EucG0YI0JPP:b-x8mics) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L116)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Do we error if merge and sheet_names are conflicting?
</blockquote></details>

not sure, will check on this
___
*[dxapp.json, line 116 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE9-vj0jKaZadxnl1Z:-MyHI0g01jbtzm4WZiBt:bfvbhc) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L116)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Not sure what a better name for this is, but something more verbose might be good.
`merge_sheets` is perhaps not quite right since it doesn't merge the filtered/unfiltered sheets but merges vcf sheets
</blockquote></details>

how about `merge_vcfs` since that is what its doing?
___
*[dxapp.json, line 121 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE9QU8Csiq66K4g4Sa:-MyHI7PbCgpCRgUH0TWp:b3ot9y9) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L121)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

How does this behave in combination with option to retaining filtered variants in the filtered sheet. One filtered sheet per vcf? One filtered sheet for all vcfs?
</blockquote></details>

filtering will always be one sheet for all filtered rows from all vcfs
___
*[dxapp.json, line 129 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE6-rI60LTtfYhycIC:-MyHIY6m2oZb0BeOcGLo:b-mbjz85) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L129)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Could this be made a little clearer? I'm not sure what it needs to be passed. What options are there? Probably relates to the `assay` input options. 
</blockquote></details>

as above, going to remove `aasay` option. Only current arg for this is dias  (since there's no summaries for the others yet). Will add to readme.
___
*[dxapp.json, line 137 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE6S9aBrJVOyEM-ERi:-MyHIjv67pxB6UZ_ZdMO:blblhaj) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L137)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Total columns as in a count, or a list of the column names, or something else?
</blockquote></details>

column names, will clarify
___
*[dxapp.json, line 142 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE6hjR43mQSsAvfvM1:-MyHInX93BRKkEu2O4dh:b-221p6f) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L142)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

I don't see anywhere that we provide a panel name.
Perhaps the help should also describe the effect that passing a bed has in the output
</blockquote></details>

true, this was left over from when I was going to panel filter still. Haven't thought much about parsing the name in, needs some thought. 
___
*[dxapp.json, line 186 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE7Osa6u3jRgwq1AvL:-MyHIzqk2xsfMYVFkLG7:bcqhk91) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob [...]

2022-03-16 16:12 UTC, mattgarner requested changes
> Reviewed 5 of 36 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64)* status: 25 of 36 files reviewed, 29 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[dxapp.json, line 27 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyIOOfh-x0klHN2iiPy:-MyIOOfh-x0klHN2iiPz:bjkpdwx) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L27)):*
> ```JSON
>     {
>       "name": "vcfs",
>       "label": "VEP annotated vcf(s)",
> ```

Do these need to be single sample vcfs? (Do we check for this?)
Any vcf version reqs?  (Do we check for this?)



_Code quote:_
```JSON
"VEP annotated vcf(s)"
```
___
*[dxapp.json, line 112 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyIUBEv6qGqdIYNhNg4:-MyIUBEv6qGqdIYNhNg5:b-940a9d) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L112)):*
> ```JSON
>       "class": "string",
>       "optional": true,
>       "help": "Prefix for naming output xlsx file",
> ```

This also overrides the sample name inside the output file, which is likely completely fine but potentially really important so perhaps describe this in the help text



_Code quote:_
```JSON
Prefix for naming output xlsx file
```
___
*[dxapp.json, line 116 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE9-vj0jKaZadxnl1Z:-MyIEw1eEl3tYN4hbqmH:b-xkz43l) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L116)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

how about `merge_vcfs` since that is what its doing?
</blockquote></details>

:joy: That makes sense
___
*[resources/home/dnanexus/generate_workbook/generate_workbook.py, line 65 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyILnK04WLf9SqtKE7c:-MyILnK17x0wI6d0lDvM:bdebr1k) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/resources/home/dnanexus/generate_workbook/generate_workbook.py#L65)):*
> ```Python
>             help=(
>                 'Columns in vcf to EXCLUDE from output, by default all INFO and '
>                 'CSQ fields are expanded to their own columns'
> ```

https://docs.python.org/3/library/argparse.html#mutual-exclusion seems appropriate for include/exclude



_Code quote:_
```Python
        parser.add_argument(
            '-e', '--exclude', nargs='+',
            help=(
                'Columns in vcf to EXCLUDE from output, by default all INFO and '
                'CSQ fields are expanded to their own columns'
            )
        )
        parser.add_argument(
            '-i', '--include', nargs='+',
            help=(
                'Columns in vcf to INCLUDE from output, by default all INFO and '
                'CSQ fields are expanded to their own columns'
            )
        )
```
___
*[resources/home/dnanexus/generate_workbook/generate_workbook.py, line 69 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyIMVX-C8YU6ZMS15Ip:-MyIMVX-C8YU6ZMS15Iq:boofnyi) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/resources/home/dnanexus/generate_workbook/generate_workbook.py#L69)):*
> ```Python
>         )
>         parser.add_argument(
>             '-i', '--include', nargs='+',
> ```

--blah_columns
See json comment
___
*[resources/home/dnanexus/generate_workbook/generate_workbook.py, line 71 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyIMiv37Tvk7fpc-fqV:-MyIMiv37Tvk7fpc-fqW:b32woa) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/resources/home/dnanexus/generate_workbook/generate_workbook.py#L71)):*
> ```Python
>             '-i', '--include', nargs='+',
>             help=(
>                 'Columns in vcf to INCLUDE from output, by default all INFO and '
> ```

in



_Code quote:_
```Python
from
```
___
*[resources/home/dnanexus/generate_workbook/generate_workbook.py, line 78 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyIMwrQBp27BrVh3Ssb:-MyIMwrQBp27BrVh3Ssc:b-ya8zyl) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/resources/home/dnanexus/generate_workbook/generate_workbook.py#L78)):*
> ```Python
>             '-r', '--reorder', required=False, nargs='+',
>             help=(
>                 'Set order for columns in output vcf, any not specified will be '
> ```

output xlsx



_Code quote:_
```Python
output vcf
```
___
*[resources/home/dnanexus/generate_workbook/generate_workbook.py, line 87 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyINC9CAHltURe8BPbg:-MyINC9CAHltURe8BPbh:bjk1291) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/resources/home/dnanexus/generate_workbook/generate_workbook.py#L87)):*
> ```Python
>                 'Pass pairs of {column_name}={new_column_name} for renaming '
>                 'columns in output excel, should be passed as '
>                 '--rename CHROM=chr POS=pos REF=ref...'
> ```

maybe include an info example? e.g. is it INFO/AF?

Similarly how to we access FORMAT fields. 

Probably matters more in dxapp.json than here



_Code quote:_
```Python
'--rename CHROM=chr POS=pos REF=ref...'
```
___
*[resources/home/dnanexus/generate_workbook/generate_workbook.py, line 106 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyIMAS9CV1Vb-DcJ9uF:-MyIMAS9CV1Vb-DcJ9uG:bfm5r82) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/resources/home/dnanexus/generate_workbook/generate_workbook.py#L106)):*
> ```Python
>         )
>         parser.add_argument(
>             '-k', '--keep', action='store_true',
> ```

--keep_filtered
see json comment



_Code quote:_
```Python
--keep
```
___
*[resources/home/dnanexus/generate_workbook/generate_workbook.py, line 142 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyIPWzfEVyyz_bvaItD:-MyIPWzfEVyyz_bvaItE:be6fbqa) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/resources/home/dnanexus/generate_workbook/generate_workbook.py#L142)):*
> ```Python
>         parser.add_argument(
>             '--out_dir', required=False, default=os.getcwd(),
>             help="path to where to output report"
> ```

path to output dir?



_Code quote:_
```Python
path to where to output report
```
___
*[resources/home/dnanexus/generate_workbook/generate_workbook.py, line 146 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyIPiwZ0sd8pooIl4rA:-MyIPiwZ0sd8pooIl4rB:bt9xe07) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/resources/home/dnanexus/generate_workbook/generate_workbook.py#L146)):*
> ```Python
>         parser.add_argument(
>             '-m', '--merge', action='store_true',
>             help='Merge multiple vcfs into one dataframe of variants to display'
> ```

presumably into one sheet, from an output perspective?



_Code quote:_
```Python
into one dataframe
```


<!-- Sent from Reviewable.io -->

2022-03-16 17:11 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64)* status: 25 of 36 files reviewed, 29 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[dxapp.json, line 42 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE8AHK6g-m6EYdl6qA:-MyIhYXa0YiR1rTWOKiH:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L42)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this is what I had before then changed it for some reason... will switch it back
</blockquote></details>

Done
___
*[dxapp.json, line 54 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE4QBe9wZyc1Zpxmb7:-MyIhRTJ274LMPxV0Erw:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L54)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/resources/home/dnanexus/generate_workbook/generate_workbook.py#L75

will add full help to app input
</blockquote></details>

Done
___
*[dxapp.json, line 62 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE4cOW6S_Cc4efANs3:-MyIhGr8BlC3K1JDOkuI:b-h5oo43) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L62)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

don't think so, will catch this and raise an error 
</blockquote></details>

Done: 

https://github.com/eastgenomics/eggd_vcf2xls_nirvana/commit/2919993aa984a48aeb41d38c896273be4000131d
___
*[dxapp.json, line 91 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE8ffEBz4Wa2aZUOQS:-MyIB-rn2WOfflQw-6i7:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L91)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

maybe `add_samplename_column`?
</blockquote></details>

Done.
___
*[dxapp.json, line 100 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE8mIN4yxlLtykd5lU:-MyIB-ak3vWjHLJuh8Us:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L100)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Maybe `sheet_names`?
</blockquote></details>

Done.
___
*[dxapp.json, line 104 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE5V9gEanhJw3vJAb9:-MyIDcgH7gLkje8jctxW:bglq0zt) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L104)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Is this one sheet per vcf? How are the names mapped to the vcfs?
</blockquote></details>

one sheet name per vcf, order must be the same as passed. Have improved the help message.
___
*[dxapp.json, line 108 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE8sZiAZqfdwVqp8WQ:-MyIDhsNCtjQLWd9bDHP:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L108)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

`output_prefix`?
</blockquote></details>

Done.
___
*[dxapp.json, line 116 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE9-vj0jKaZadxnl1Z:-MyIDk_JEYTKqlK11vDz:b-o4uopv) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L116)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

how about `merge_vcfs` since that is what its doing?
</blockquote></details>

gone with `merge_vcfs`
___
*[dxapp.json, line 129 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE6-rI60LTtfYhycIC:-MyIVrUV6Q8SIw2oMlIm:bnh7znl) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L129)):*
> as above, going to remove aasay option. Only current arg for this is dias  (since there's no summaries for the others yet). Will add to readme.
Done.
___
*[dxapp.json, line 137 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE6S9aBrJVOyEM-ERi:-MyIDymKCPcEl_d-JD_a:bb7f2mf) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L137)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

column names, will clarify
</blockquote></details>

done
___
*[dxapp.json, line 142 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE6hjR43mQSsAvfvM1:-MyIVwAf28RtyM-nV_FQ:bb7462z) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L142)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

true, this was left over from when I was going to panel filter still. Haven't thought much about parsing the name in, needs some thought. 
</blockquote></details>

TODO
___
*[Readme.md, line 16 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE7tSIATwqflD5wa3f:-MyIW-2yBoR7pWdXGp_j:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/Readme.md#L16)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

htslib?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-17 10:17 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64)* status: 26 of 36 files reviewed, 22 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[Readme.md, line 80 at r4](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyIf6BICBsoVibgOym9:-MyMJccl0xRsmm9riZ4j:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/cbc4fd57c7878506711c848825458cb32403d038/Readme.md#L80)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

double space
</blockquote></details>

Done.
___
*[resources/home/dnanexus/generate_workbook/generate_workbook.py, line 65 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyILnK04WLf9SqtKE7c:-MyMK77t8zJZbBvUkyTD:bgmcxqe) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/resources/home/dnanexus/generate_workbook/generate_workbook.py#L65)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

https://docs.python.org/3/library/argparse.html#mutual-exclusion seems appropriate for include/exclude
</blockquote></details>

True, was being lazy and threw and asset in, changed to use a group
___
*[resources/home/dnanexus/generate_workbook/generate_workbook.py, line 71 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyIMiv37Tvk7fpc-fqV:-MyMKG4IDR5HkJ29QjXz:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/resources/home/dnanexus/generate_workbook/generate_workbook.py#L71)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

in
</blockquote></details>

Done.
___
*[resources/home/dnanexus/generate_workbook/generate_workbook.py, line 87 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyINC9CAHltURe8BPbg:-MyMKbis75hSrzVPxQQz:bu0pto4) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/resources/home/dnanexus/generate_workbook/generate_workbook.py#L87)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

maybe include an info example? e.g. is it INFO/AF?

Similarly how to we access FORMAT fields. 

Probably matters more in dxapp.json than here
</blockquote></details>

this is after columns are split out, info columns just have their name, and format if already present in INFO will have a `(FMT)` suffix. Will add this to readme. For renaming there is the `--print_columns` method to know what column names there are
___
*[resources/home/dnanexus/generate_workbook/generate_workbook.py, line 142 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyIPWzfEVyyz_bvaItD:-MyMLrMXDzRzkZXaQ8yC:b-7atzx4) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/resources/home/dnanexus/generate_workbook/generate_workbook.py#L142)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

path to output dir?
</blockquote></details>

that would be more sensible yes, changed it
___
*[resources/home/dnanexus/generate_workbook/generate_workbook.py, line 146 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyIPiwZ0sd8pooIl4rA:-MyMM0GP56ApG4oj3p7a:buduisu) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/resources/home/dnanexus/generate_workbook/generate_workbook.py#L146)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

presumably into one sheet, from an output perspective?
</blockquote></details>

yep that one
___
*[resources/home/dnanexus/generate_workbook/utils/vcf.py, line 26 at r4](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyIhDMPCfk49Fh5VHaQ:-MyMM3_TDiDoSn2dXNo2:bpeke13) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/cbc4fd57c7878506711c848825458cb32403d038/resources/home/dnanexus/generate_workbook/utils/vcf.py#L26)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Placing a note as a reminder to check - it would be good to have the ref build in the report summary
</blockquote></details>

That's what I was parsing them from the vcf for, thought I had already added it the dias summary, will go check
___
*[resources/home/dnanexus/generate_workbook/utils/vcf.py, line 80 at r4](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyIiUPWCTkmhNxEse3E:-MyMMN0m4S4ylX-wDp3H:b-ycrukz) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/cbc4fd57c7878506711c848825458cb32403d038/resources/home/dnanexus/generate_workbook/utils/vcf.py#L80)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

This is quite an edge case but

If you pass multiple vcfs with the same name (which would not be good practice, but is not a problem for dx) then this would generate multiple intermediates with the same name, which is a problem locally.
</blockquote></details>

that is true, it would overwrite it :upside_down_face:  will have a think about a non-convoluted way to handle this 
___
*[resources/home/dnanexus/generate_workbook/utils/vcf.py, line 139 at r4](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyIkuCTBbe6Kae60MKG:-MyMM_Vx1k_C4j2_AXKi:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/cbc4fd57c7878506711c848825458cb32403d038/resources/home/dnanexus/generate_workbook/utils/vcf.py#L139)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

column
</blockquote></details>

Done.
___
*[resources/home/dnanexus/generate_workbook/utils/vcf.py, line 185 at r4](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyIm4jg4xiVWYMcy5sb:-MyMN-X1BRbu8HEbCQ2m:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/cbc4fd57c7878506711c848825458cb32403d038/resources/home/dnanexus/generate_workbook/utils/vcf.py#L185)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

could use -Ou for speedier piping
```
-O, --output-type b|u|z|v[0-9]

    Output compressed BCF (b), uncompressed BCF (u), compressed VCF (z), uncompressed VCF (v). Use the -Ou option when piping between bcftools subcommands to speed up performance by removing unnecessary compression/decompression and VCF←→BCF conversion.
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-17 10:17 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64)* status: 26 of 36 files reviewed, 22 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[resources/home/dnanexus/generate_workbook/generate_workbook.py, line 87 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyINC9CAHltURe8BPbg:-MyMNYaoBpisgkJNu_Md:b-3833ub) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/resources/home/dnanexus/generate_workbook/generate_workbook.py#L87)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this is after columns are split out, info columns just have their name, and format if already present in INFO will have a `(FMT)` suffix. Will add this to readme. For renaming there is the `--print_columns` method to know what column names there are
</blockquote></details>

https://github.com/eastgenomics/eggd_vcf2xls_nirvana/commit/aee1555da2c2f20b66bececc044a622288701a4b


<!-- Sent from Reviewable.io -->

2022-03-17 11:06 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64)* status: 26 of 36 files reviewed, 22 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[dxapp.json, line 70 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE4r3S5IgEwcy4q7zb:-MyMST-X8UYgliQ_Nl0R:b-4h2z8y) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L70)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

Yep will do, on my to do list to add a section to the  readme, found some comprehensive examples I can link to
</blockquote></details>

Added to readme
___
*[dxapp.json, line 104 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE5V9gEanhJw3vJAb9:-MyMSeVW0HQAaulpWaqu:b32wjj) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L104)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

e
</blockquote></details>

e?
___
*[dxapp.json, line 112 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyIUBEv6qGqdIYNhNg4:-MyMXHzp9hw30tPgejsH:bhx550m) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L112)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

This also overrides the sample name inside the output file, which is likely completely fine but potentially really important so perhaps describe this in the help text
</blockquote></details>

the sample name to the output sheet will always come from the file name and not the sheet names or the prefix, the prefix is just for output naming:

https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/caf16d1e8eba0be591ce73a147f08087bc697200/resources/home/dnanexus/generate_workbook/utils/vcf.py#L244

which is called here: https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/caf16d1e8eba0be591ce73a147f08087bc697200/resources/home/dnanexus/generate_workbook/utils/vcf.py#L118

the `sample_name` passed is always from `Path(vcf).stem`.

I was more thinking `--add_name` would be used with `--merge`, doesn't seem that useful if they're still split in separate sheets.

I do have a `--sample` argument left in the python script but it isn't used anywhere and I don't remember why... (I think this old and I changed my mind on naming).
___
*[resources/home/dnanexus/generate_workbook/generate_workbook.py, line 78 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyIMwrQBp27BrVh3Ssb:-MyMSp69CoSW4VervRBX:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/resources/home/dnanexus/generate_workbook/generate_workbook.py#L78)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

output xlsx
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-17 11:11 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64)* status: 26 of 36 files reviewed, 22 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[dxapp.json, line 112 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyIUBEv6qGqdIYNhNg4:-MyMZc33-zPdtLWoo-xm:bedlhs3) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L112)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

the sample name to the output sheet will always come from the file name and not the sheet names or the prefix, the prefix is just for output naming:

https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/caf16d1e8eba0be591ce73a147f08087bc697200/resources/home/dnanexus/generate_workbook/utils/vcf.py#L244

which is called here: https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/caf16d1e8eba0be591ce73a147f08087bc697200/resources/home/dnanexus/generate_workbook/utils/vcf.py#L118

the `sample_name` passed is always from `Path(vcf).stem`.

I was more thinking `--add_name` would be used with `--merge`, doesn't seem that useful if they're still split in separate sheets.

I do have a `--sample` argument left in the python script but it isn't used anywhere and I don't remember why... (I think this old and I changed my mind on naming).
</blockquote></details>

oohhh I think I was thinking it was to add the sample name into the summary sheet for Dias like they currently have (although this doesn't need a separate argument and I can just parse it from the filename I guess)


<!-- Sent from Reviewable.io -->

2022-03-17 15:01 UTC, mattgarner requested changes
> Reviewed 1 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64)* status: 26 of 36 files reviewed, 24 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[resources/home/dnanexus/generate_workbook/utils/vcf.py, line 306 at r8](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyNGFue9q3z1KoUa1Bp:-MyNGFue9q3z1KoUa1Bq:bvqbg4p) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/3a7bfd99094c88c4c99c920cd292c1c80d6c05e5/resources/home/dnanexus/generate_workbook/utils/vcf.py#L306)):*
> ```Python
>         fh.close
> 
>         columns = [x.strip('#') for x in header[-1].split()]
> ```

Is it worth putting an assert in here for `columns[0] == "#CHROM"` ?

Just in case the vcf header is missing column headers for some reason



_Code quote:_
```Python
columns
```
___
*[resources/home/dnanexus/generate_workbook/utils/vcf.py, line 338 at r8](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyNHVaO0lyOxu3PPx7b:-MyNHVaO0lyOxu3PPx7c:b-bagi1w) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/3a7bfd99094c88c4c99c920cd292c1c80d6c05e5/resources/home/dnanexus/generate_workbook/utils/vcf.py#L338)):*
> ```Python
>         if '37' in reference or 'hg19' in reference:
>             self.urls.update({
>                 "gnomad_af": "https://gnomad.broadinstitute.org/variant/CHROM-POS-REF-ALT?dataset=gnomad_r2_1",
> ```

I can't see a sensible way to make this point to the latest release for the intended build, so this makes sense



_Code quote:_
```Python
dataset=gnomad_r2_1
```
___
*[resources/home/dnanexus/generate_workbook/utils/vcf.py, line 350 at r8](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyNHv_FBkdtkYXSe7T2:-MyNHv_FBkdtkYXSe7T3:bk4chku) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/3a7bfd99094c88c4c99c920cd292c1c80d6c05e5/resources/home/dnanexus/generate_workbook/utils/vcf.py#L350)):*
> ```Python
>             for col in vcf.columns:
>                 # print(vcf.columns.tolist())
>                 # sys.exit()
> ```

Clean up needed



_Code quote:_
```Python
                # print(vcf.columns.tolist())
                # sys.exit()
```
___
*[resources/home/dnanexus/generate_workbook/utils/vcf.py, line 470 at r8](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyNLN2t7pjNDBvsGmfl:-MyNLN2t7pjNDBvsGmfm:b-l02h7x) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/3a7bfd99094c88c4c99c920cd292c1c80d6c05e5/resources/home/dnanexus/generate_workbook/utils/vcf.py#L470)):*
> ```Python
>                     set(vcf.columns.tolist()) - set(columns)
>                 )
>             else:
> ```

So the code which calls this right now means that it would never be called if neither include or exclude were true, but... 
```
if args.include:
...
else:
 - Case 1 - args.include == False and args.exclude == True
 - Case 2 - args.include == False and args.exclude == False
```
We assume Case 1

Would it be safer to handle the cases separately just in case someone makes a future change without realising the context in which this is currently used?
i.e.
```
if include:
...
elif exclude:
...
else:
yikes
```



_Code quote:_
```Python
else:
```
___
*[resources/home/dnanexus/generate_workbook/utils/vcf.py, line 515 at r8](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyNNcNJ0aG363Slv3tN:-MyNNcNJ0aG363Slv3tO:b-xfs1go) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/3a7bfd99094c88c4c99c920cd292c1c80d6c05e5/resources/home/dnanexus/generate_workbook/utils/vcf.py#L515)):*
> ```Python
>         """
>         Rename columnns from key value pairs passed from --rename argument,
>         also remove underscores from all names for nicer reading
> ```

Should this be a separate function? Is there ever a need to perform this on non-renamed columns?



_Code quote:_
```Python
also remove underscores from all names for nicer reading
```


<!-- Sent from Reviewable.io -->

2022-03-17 15:48 UTC, mattgarner requested changes
> Reviewed 1 of 36 files at r1, 1 of 5 files at r3, 2 of 4 files at r6, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64)* status: 33 of 36 files reviewed, 19 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[resources/home/dnanexus/generate_workbook/utils/columns.py, line 94 at r8](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyNX5aD6i_FWeJgM1l5:-MyNX5aD6i_FWeJgM1l6:b-geyric) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/3a7bfd99094c88c4c99c920cd292c1c80d6c05e5/resources/home/dnanexus/generate_workbook/utils/columns.py#L94)):*
> ```Python
>         # before -> GT:AD:DP:GQ:PL  1/1:0,41:41:99:1442,123,0
>         # after  -> GT=1/1##AD=0,41##DP=41##GQ=99##PL=1442,123,0
>         # n.b. using '##' to join since VCF spec for what is allowed in
> ```

Could add a check that there is no ## in the stings before splitting, but as you say it's very very unlikely



_Code quote:_
```Python
        # n.b. using '##' to join since VCF spec for what is allowed in
        # sample strings is not strict, but ## is very unlikely to be used
```
___
*[resources/home/dnanexus/generate_workbook/utils/excel.py, line 404 at r8](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyNSeSv3JPAyDRyz1OM:-MyNSeSv3JPAyDRyz1ON:bc37fwv) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/3a7bfd99094c88c4c99c920cd292c1c80d6c05e5/resources/home/dnanexus/generate_workbook/utils/excel.py#L404)):*
> ```Python
>             # loop over column names, select width by closest match from dict
>             # and set width in sheet letter
>             width = self.get_closest_match(column.lower(), widths)
> ```

Could we set a minimum width to ensure columns are always visible, not hidden by having 0 or tiny width?



_Code quote:_
```Python
width = self.get_closest_match(column.lower(), widths)
```
___
*[resources/home/dnanexus/generate_workbook/utils/vcf.py, line 26 at r4](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyIhDMPCfk49Fh5VHaQ:-MyNQC0E7vQMfqR3KyQj:bbj2518) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/cbc4fd57c7878506711c848825458cb32403d038/resources/home/dnanexus/generate_workbook/utils/vcf.py#L26)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

That's what I was parsing them from the vcf for, thought I had already added it the dias summary, will go check
</blockquote></details>

When passing multiple vcfs, do they all have to be the same build? Or rather, do we check that they are?


<!-- Sent from Reviewable.io -->

2022-03-17 16:54 UTC, mattgarner requested changes
> Reviewed 1 of 36 files at r1, 2 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64)* status: 32 of 36 files reviewed, 21 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[resources/home/dnanexus/generate_workbook/tests/test_columns.py, line 136 at r8](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyNjwIFCYiMXxspM-Lt:-MyNjwIFCYiMXxspM-Lu:b-rtm2q) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/3a7bfd99094c88c4c99c920cd292c1c80d6c05e5/resources/home/dnanexus/generate_workbook/tests/test_columns.py#L136)):*
> ```Python
>         assert set(df_values) - set(stdout) == set(), (
>             "gnomAD AF values present in dataframe not in VCF"
>         )
> ```

Possibility for this check to not catch missing values in df
```
vcf values:
0.1
0.1
0.2
stdout = {0.1, 0.2}

df:
0.1

0.2
df_values = {0.1, 0.2}

assert set(stdout) - set(df_values)
True
```



_Code quote:_
```Python
 )
```
___
*[resources/home/dnanexus/generate_workbook/tests/test_columns.py, line 145 at r8](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyNlBX7A16Vijz-ztr-:-MyNlBX7A16Vijz-ztr0:b-3ic2ax) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/3a7bfd99094c88c4c99c920cd292c1c80d6c05e5/resources/home/dnanexus/generate_workbook/tests/test_columns.py#L145)):*
> ```Python
>     """
>     # run dataframe through splitColumns.format_fields() to split out FORMAT/SAMPLE
>     test_vcf = "NA12878_unittest.split.vcf"
> ```

Should this be using TEST_DATA_DIR to construct the path?



_Code quote:_
```Python
"NA12878_unittest.split.vcf"
```


<!-- Sent from Reviewable.io -->

2022-03-17 17:24 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64)* status: 31 of 36 files reviewed, 21 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[dxapp.json, line 27 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyIOOfh-x0klHN2iiPy:-MyNmlkp15bO5GjC9ZRw:bxhmx29) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L27)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Do these need to be single sample vcfs? (Do we check for this?)
Any vcf version reqs?  (Do we check for this?)
</blockquote></details>

We don't and we should, multi would break this. What can we reliably check on?

vcf version I don't think would break things, do you know what we have now?
___
*[dxapp.json, line 38 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE49Lo-PIu2ZENFe3n:-MyNn6qj73bXgDvekbU0:b-yz45jr) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L38)):*
> mn is passed 
Added mutually exclusive group for include/exclude so not an issue
___
*[dxapp.json, line 74 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE5A-kBeHLEzyUXPRa:-MyNnDIfE5M519jx2Ex1:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L74)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

good idea, will do
</blockquote></details>

Done
___
*[dxapp.json, line 116 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE5ic20J9C4Y9cF8oQ:-MyNpQxw1tGJbTB79yTZ:b-acyzuq) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L116)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

not sure, will check on this
</blockquote></details>

Added check:

https://github.com/eastgenomics/eggd_vcf2xls_nirvana/commit/45459a762afafb443ac40c27140ada8a86f35e9c
___
*[resources/home/dnanexus/generate_workbook/utils/vcf.py, line 26 at r4](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyIhDMPCfk49Fh5VHaQ:-MyNpd9tCj3ZHp9x5M8h:bfs2b8h) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/cbc4fd57c7878506711c848825458cb32403d038/resources/home/dnanexus/generate_workbook/utils/vcf.py#L26)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

When passing multiple vcfs, do they all have to be the same build? Or rather, do we check that they are?
</blockquote></details>

They don't have to be (and I don't think we would)? If there is more than one they will be added as a comma separated list
___
*[resources/home/dnanexus/generate_workbook/utils/vcf.py, line 306 at r8](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyNGFue9q3z1KoUa1Bp:-MyNqUqJDGskeAAUY0wd:b-1sae7) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/3a7bfd99094c88c4c99c920cd292c1c80d6c05e5/resources/home/dnanexus/generate_workbook/utils/vcf.py#L306)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Is it worth putting an assert in here for `columns[0] == "#CHROM"` ?

Just in case the vcf header is missing column headers for some reason
</blockquote></details>

seems sensible, done: https://github.com/eastgenomics/eggd_vcf2xls_nirvana/commit/348647c7517d43b40062e51b513ac911dd844e0d
___
*[resources/home/dnanexus/generate_workbook/utils/vcf.py, line 338 at r8](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyNHVaO0lyOxu3PPx7b:-MyNqlzABANygb1bFluy:b28bo9j) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/3a7bfd99094c88c4c99c920cd292c1c80d6c05e5/resources/home/dnanexus/generate_workbook/utils/vcf.py#L338)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

I can't see a sensible way to make this point to the latest release for the intended build, so this makes sense
</blockquote></details>

At worst if it doesn't match the links just won't get added, gnomAD is the only one like this and this seemed the easiest way to handle it. Have split out the base url to make it slightly clearer / less pep8 anger:

https://github.com/eastgenomics/eggd_vcf2xls_nirvana/commit/ba27950e1bd8cdab23f3d3fc017742e25f934022
___
*[resources/home/dnanexus/generate_workbook/utils/vcf.py, line 350 at r8](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyNHv_FBkdtkYXSe7T2:-MyNql5oALVtsKD6Q2Fm:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/3a7bfd99094c88c4c99c920cd292c1c80d6c05e5/resources/home/dnanexus/generate_workbook/utils/vcf.py#L350)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Clean up needed
</blockquote></details>

Done.
___
*[resources/home/dnanexus/generate_workbook/utils/vcf.py, line 470 at r8](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyNLN2t7pjNDBvsGmfl:-MyNstz729DJQWQMq1z8:b-qad82q) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/3a7bfd99094c88c4c99c920cd292c1c80d6c05e5/resources/home/dnanexus/generate_workbook/utils/vcf.py#L470)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

So the code which calls this right now means that it would never be called if neither include or exclude were true, but... 
```
if args.include:
...
else:
 - Case 1 - args.include == False and args.exclude == True
 - Case 2 - args.include == False and args.exclude == False
```
We assume Case 1

Would it be safer to handle the cases separately just in case someone makes a future change without realising the context in which this is currently used?
i.e.
```
if include:
...
elif exclude:
...
else:
yikes
```
</blockquote></details>

Well I would hope my tests would fail, but that seems sensible to explicitly handle both, have changed it so it continues if neither are specified (not that it should get here if they aren't):

https://github.com/eastgenomics/eggd_vcf2xls_nirvana/commit/7058929c9ea420311d52734901f374cab00dc0a7
___
*[resources/home/dnanexus/generate_workbook/utils/vcf.py, line 515 at r8](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyNNcNJ0aG363Slv3tN:-MyNtcgpCSk6dDqli93k:brqy43d) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/3a7bfd99094c88c4c99c920cd292c1c80d6c05e5/resources/home/dnanexus/generate_workbook/utils/vcf.py#L515)):*
> renamed
`rename_columns()` always called from `process()` and stripping the underscores is of outside the `if self.args.rename:...` block. 

It is called as the last function since it changes the names and to not interfere with other functions


<!-- Sent from Reviewable.io -->

2022-03-17 17:25 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64)* status: 31 of 36 files reviewed, 21 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[dxapp.json, line 27 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyIOOfh-x0klHN2iiPy:-MyNuEDX2v4paIwEO5DT:b3y64jz) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L27)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

We don't and we should, multi would break this. What can we reliably check on?

vcf version I don't think would break things, do you know what we have now?
</blockquote></details>

actually a mix of 37 and 38 wouldn't be ideal as the gnomAD URLs may be incorrect, want me to exit on mixed ones?


<!-- Sent from Reviewable.io -->

2022-03-17 21:25 UTC, mattgarner requested changes
> Reviewed 2 of 3 files at r10, 2 of 3 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64)* status: all files reviewed, 15 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[dxapp.json, line 27 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyIOOfh-x0klHN2iiPy:-MyOjI3ZEw4BoFjmvQfO:b-7h23jt) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L27)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

actually a mix of 37 and 38 wouldn't be ideal as the gnomAD URLs may be incorrect, want me to exit on mixed ones?
</blockquote></details>

Mixed refs would be bad, certainly exit on that. Might be a bit annoying to set up as different things could use different filenames for the same build e.g. masked or unmasked 38, both 38 but different files. I guess both would still have 38 in the filename

I think I commented on that elsewhere too. Mixed versions are not such a big deal. 
___
*[resources/home/dnanexus/generate_workbook/utils/vcf.py, line 26 at r4](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyIhDMPCfk49Fh5VHaQ:-MyOknlI5u8wj4lxCuMK:bw2xe7h) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/cbc4fd57c7878506711c848825458cb32403d038/resources/home/dnanexus/generate_workbook/utils/vcf.py#L26)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

They don't have to be (and I don't think we would)? If there is more than one they will be added as a comma separated list
</blockquote></details>

Discussed elsewhere, so resolving this thread


<!-- Sent from Reviewable.io -->

2022-03-18 14:38 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64)* status: 34 of 36 files reviewed, 15 unresolved discussions (waiting on @mattgarner)

___
*[dxapp.json, line 27 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyIOOfh-x0klHN2iiPy:-MySO_UVBjSnzleaZywy:b-jsrbsx) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L27)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Mixed refs would be bad, certainly exit on that. Might be a bit annoying to set up as different things could use different filenames for the same build e.g. masked or unmasked 38, both 38 but different files. I guess both would still have 38 in the filename

I think I commented on that elsewhere too. Mixed versions are not such a big deal. 
</blockquote></details>

Done: 

https://github.com/eastgenomics/eggd_vcf2xls_nirvana/commit/811abbf1cfba406b5bf8188bdf41bb692e9e4a1e
___
*[resources/home/dnanexus/generate_workbook/tests/test_columns.py, line 136 at r8](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyNjwIFCYiMXxspM-Lt:-MySQiXACtX1laBEhfs7:b-reli83) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/3a7bfd99094c88c4c99c920cd292c1c80d6c05e5/resources/home/dnanexus/generate_workbook/tests/test_columns.py#L136)):*
Changed to this:
```
>>> l1=[1,2,3,4]
>>> l2=[1,2,3,4]
>>> all([x == y for x, y in zip(l1, l2)])
True
>>> l3=[1,2,'',3,4]
>>> all([str(x) == str(y) for x, y in zip(l1, l3)])
False
```
___
*[resources/home/dnanexus/generate_workbook/tests/test_columns.py, line 145 at r8](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyNlBX7A16Vijz-ztr-:-MySSVLB0HuLjzkyM4WJ:bs297pp) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/3a7bfd99094c88c4c99c920cd292c1c80d6c05e5/resources/home/dnanexus/generate_workbook/tests/test_columns.py#L145)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Should this be using TEST_DATA_DIR to construct the path?
</blockquote></details>

yep, was using wrong one
___
*[resources/home/dnanexus/generate_workbook/utils/vcf.py, line 80 at r4](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyIiUPWCTkmhNxEse3E:-MySS_jI-k_jID1ZPWmm:b-js2tj0) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/cbc4fd57c7878506711c848825458cb32403d038/resources/home/dnanexus/generate_workbook/utils/vcf.py#L80)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

that is true, it would overwrite it :upside_down_face:  will have a think about a non-convoluted way to handle this 
</blockquote></details>

writing this down to remember later (or might just add an exit on same named vcfs if I can't handle it nicely)... will think about it and come back to it


<!-- Sent from Reviewable.io -->

2022-03-18 17:28 UTC, mattgarner reviewed
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64)* status: all files reviewed, 2 unresolved discussions (waiting on @mattgarner)

___
*[dxapp.json, line 104 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-MyE5V9gEanhJw3vJAb9:-MyT-HVi57N1X59u20c-:bkwau7x) ([raw file](https://github.com/eastgenomics/eggd_vcf2xls_nirvana/blob/50d1c9412df266c8bb8426a3894ea77717921b8d/dxapp.json#L104)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

e?
</blockquote></details>

no idea...


<!-- Sent from Reviewable.io -->

2022-03-18 17:41 UTC, mattgarner approved these changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2022-03-18 17:45 UTC, jethror1 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/64#-:-MyT7bVY1SW1egKo1wGI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2022-03-18 18:21 UTC, merged